name = "argos"
description = "A Bootstrap-based theme for Hugo."
homepage = "https://github.com/nanxstats/bco-public-website"
tags = ["bootstrap", "responsive"]
min_version = 0.17

[author]
  name = "Hadley King"
  homepage = "https://github.com/HadleyKing"
  repo = "https://github.com/FDA-ARGOS2/argosdb/"
